### Login Request
POST http://localhost:3000/auth/login
Content-Type: application/json

# Aluno
{
  "cpf": "12345678315",
  "password": "13032003"
}

# Professor
# {
#   "cpf": "01987654325",
#   "password": "123456"
# }

###

### Create - Beacon
POST http://localhost:3000/beacons
Content-Type: application/json

{
  "uuid": "ah23789-ga12dw",
  "subjectId": 1,
  "classroomId": 5,
  "teacherId": 1
}
###

### Get All - Beacon 
GET http://localhost:3000/beacons
###

### Get by Id - Beacon
GET http://localhost:3000/beacons/13

### Update - Beacon
PATCH http://localhost:3000/beacons/13
Content-Type: application/json


{
  "id": 13,
  "uuid": "UUIDMODIFICADO",
  "subjectId": 1,
  "classroomId": 1,
  "teacherId": 1
}
###

### Delete - Beacon
DELETE http://localhost:3000/beacons/13
###


### Create - Classroom
POST http://localhost:3000/classrooms
Content-Type: application/json

{
  "labNumber": 3,
  "subjectId": 1
}
###

### Get All - Classroom
GET http://localhost:3000/classrooms
###

### Get by Id - Classroom
GET http://localhost:3000/classrooms/3
###

### Update - Classroom
PATCH http://localhost:3000/classrooms/3
Content-Type: application/json

{
  "labNumber": 11,
  "subjectId": 1
}
###

### Delete - Classroom
DELETE http://localhost:3000/classrooms/6
###



### Create - Course
POST http://localhost:3000/courses
Content-Type: application/json

{
  "name": "Arq. e Urb.",
  "description": "Bacharelado em Arquitetura e Urbanismo",
  "subjects": [1, 2, 3],
  "students": [6]
}

###

### Get All - Course
GET http://localhost:3000/courses
###

### Get by Id - Course
GET http://localhost:3000/courses/2
###

### Update - Course
PATCH  http://localhost:3000/courses/3
Content-Type: application/json

{
  "name": "Sistemas de Conexão",
  "description": "Curso de Sistemas de Conexão",
  "subjectId": 1,
  "studentId": 126234
}
###

### Delete - Course
DELETE http://localhost:3000/courses/3
###



### Create - Subject
POST http://localhost:3000/subjects
Content-Type: application/json

{
  "name": "Gerenciamento de Projetos",
  "description": "Aula de Gerenciamento de Projetos",
  "workload": 120
}

###

### Get All - Subject
GET http://localhost:3000/subjects
###

### Get by Id - Subject
GET http://localhost:3000/subjects/3
###

### Update - Subject
PATCH http://localhost:3000/subjects/4
Content-Type: application/json

{
  "name": "O.O.P.",
  "description": "Aula de O.O.P.",
  "workload": 180
}
###

### Delete - Subject
DELETE http://localhost:3000/subjects/3
###



### Create - Student
POST http://localhost:3000/students
Content-Type: application/json

{
  "cpf": "12345678314",
  "academicalRegister": "2242472",
  "name": "nikollas",
  "email": "nikollas@email.com",
  "birthDate": "2003-03-13",
  "subjects": [1, 2, 3],
  "courses": [1]
}

###

### Get All - Student
GET http://localhost:3000/students
###

### Get by Id - Student
GET http://localhost:3000/students/123
###

### Update - Student
PATCH http://localhost:3000/students/4
Content-Type: application/json

{
  "id": 4,
  "cpf": "12345678315",
  "academicalRegister": "2242471",
  "name": "nikollas updated",
  "email": "nikollas@updated.com",
  "password": "13032003",
  "subjects": [1, 2, 3],
  "courses": [1]
}
###

### Delete - Student
DELETE http://localhost:3000/students/123
###


### Create - Teacher
POST http://localhost:3000/teachers
Content-Type: application/json

{
  "name": "joão clementino",
  "cpf": "01987654352"
}

###

### Get All - Teacher
GET http://localhost:3000/teachers
###

### Get by Id - Teacher
GET http://localhost:3000/teachers/1
###

### Update - Teacher
PATCH http://localhost:3000/teachers/1
Content-Type: application/json

{
  "password": "123456",
  "subjects": [1, 2]
}
###

### Delete - Teacher
DELETE http://localhost:3000/teachers/3
###