
### Var
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbSIsImVtYWlsIjoiYWRtQGVtYWlsLmNvbSIsImlhdCI6MTcxOTE3MjA0MSwiZXhwIjoxNzE5Nzc2ODQxfQ.RxTUGw1xNAnBUsa5DkwlwxUyq4OJ5jHb4KCKWfQ7jlg
@url = http://localhost:3000

### Login Request
POST {{url}}/auth/login
Content-Type: application/json

# Aluno
{
  "id": 2,
  "password": "123"
}

### Create - Beacon
POST {{url}}/beacons
token: {{token}}
Content-Type: application/json

{
  "uuid": "ea332d85-7070-4515-8e6c-36d32b5feaf4",
  "subjectId": 1,
  "classroomId": 5,
  "teacherId": 1
}
###

### Get All - Beacon 
GET {{url}}/beacons
token: {{token}}
###

### Get by Id - Beacon
GET {{url}}/beacons/1
token: {{token}}


### Create - Classroom
POST {{url}}/classrooms
token: {{token}}
Content-Type: application/json

{
  "labNumber": 3,
  "subjectId": 1
}
###

### Get All - Classroom
GET {{url}}/classrooms
token: {{token}}
###

### Get by Id - Classroom
GET {{url}}/classrooms/7
token: {{token}}
###

### Update - Classroom
PATCH {{url}}/classrooms/7
token: {{token}}
Content-Type: application/json

{
  "labNumber": 50,
  "subjectId": 1
}
###

### Delete - Classroom
DELETE {{url}}/classrooms/7
token: {{token}}
###



### Create - Course
POST {{url}}/courses
token: {{token}}
Content-Type: application/json

{
  "name": "Sis. Informação",
  "description": "Bacharelado em Sis. Informação",
  "subjects": [1, 2, 3],
  "students": [6]
}

###

### Get All - Course
GET {{url}}/courses
token: {{token}}
###

### Get by Id - Course
GET {{url}}/courses/7
token: {{token}}
###

### Update - Course
PATCH  {{url}}/courses/8
token: {{token}}
Content-Type: application/json

{
  "name": "Sistemas de Conexão",
  "description": "Curso de Sistemas de Conexão",
  "subjectId": 1,
  "studentId": 126234
}
###

### Delete - Course
DELETE {{url}}/courses/3
token: {{token}}
###



### Create - Subject
POST {{url}}/subjects
token: {{token}}
Content-Type: application/json

{
  "name": "Gerenciamento de Projetos",
  "description": "Aula de Gerenciamento de Projetos",
  "workload": 120
}

###

### Get All - Subject
GET {{url}}/subjects
token: {{token}}
###

### Get by Id - Subject
GET {{url}}/subjects/3
token: {{token}}
###

### Update - Subject
PATCH {{url}}/subjects/4
token: {{token}}
Content-Type: application/json

{
  "name": "O.O.P.",
  "description": "Aula de O.O.P.",
  "workload": 180
}
###

### Delete - Subject
DELETE {{url}}/subjects/3
token: {{token}}
###



### Create - Student
POST {{url}}/students
token: {{token}}
Content-Type: application/json

{
  "cpf": "12345678314",
  "academicalRegister": "2242472",
  "name": "nikollas",
  "email": "nikollas@email.com",
  "birthDate": "2003-03-13",
  "subjects": [1, 2, 3],
  "courses": [1]
}

###

### Get All - Student
GET {{url}}/students
token: {{token}}
token: 
###

### Get by Id - Student
GET {{url}}/students/123
token: {{token}}
###

### Update - Student
PATCH {{url}}/students/4
token: {{token}}
Content-Type: application/json

{
  "id": 4,
  "cpf": "12345678315",
  "academicalRegister": "2242471",
  "name": "nikollas updated",
  "email": "nikollas@updated.com",
  "password": "13032003",
  "subjects": [1, 2, 3],
  "courses": [1]
}
###

### Delete - Student
DELETE {{url}}/students/123
token: {{token}}
###


### Create - Teacher
POST {{url}}/teachers
token: {{token}}
Content-Type: application/json

{
  "name": "joão teste",
  "cpf": "01987654353",
  "email": "joao.teste@email.com",
  "subjects": [1, 2]
}

###

### Get All - Teacher
GET {{url}}/teachers
token: {{token}}
###

### Get by Id - Teacher
GET {{url}}/teachers/1
token: {{token}}
###

### Update - Teacher
PATCH {{url}}/teachers/1
token: {{token}}
Content-Type: application/json

{
  "password": "123456",
  "subjects": [1, 2]
}
###

### Delete - Teacher
DELETE {{url}}/teachers/3
token: {{token}}
###